In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.read_csv('drug200.csv')

In [ ]:
df.head()


Age  Sex  BP Cholesterol  Na_to_K  Drug
0   23    0   0        HIGH   25.355     0
1   47    1   1        HIGH   13.093     3
2   47    1   1        HIGH   10.114     3
3   28    0   2        HIGH    7.798     4
4   61    0   1        HIGH   18.043     0

In [ ]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
unique_values = df['Drug'].unique()
value_counts = df['Drug'].value_counts()

print("Unique Values:", unique_values)
print("\nValue Counts:\n", value_counts)


Unique Values: [0 3 4 1 2]

Value Counts:
 0    91
4    54
1    23
3    16
2    16
Name: Drug, dtype: int64


In [ ]:
x = df.iloc[:,1:5].values
x

array([[0, 0, 'HIGH', 25.355],
       [1, 1, 'HIGH', 13.093],
       [1, 1, 'HIGH', 10.114],
       [0, 2, 'HIGH', 7.798],
       [0, 1, 'HIGH', 18.043],
       [0, 2, 'HIGH', 8.607],
       [0, 2, 'HIGH', 16.275],
       [1, 1, 'HIGH', 11.037],
       [1, 2, 'HIGH', 15.171],
       [1, 1, 'NORMAL', 19.368],
       [0, 1, 'HIGH', 11.767],
       [0, 0, 'NORMAL', 19.199],
       [1, 1, 'HIGH', 15.376],
       [0, 1, 'HIGH', 20.942],
       [0, 2, 'HIGH', 12.703],
       [0, 0, 'NORMAL', 15.516],
       [1, 1, 'NORMAL', 11.455],
       [1, 0, 'HIGH', 13.972],
       [1, 1, 'HIGH', 7.298],
       [0, 0, 'NORMAL', 25.974],
       [1, 1, 'NORMAL', 19.128],
       [1, 2, 'HIGH', 25.917],
       [1, 1, 'NORMAL', 30.568],
       [0, 1, 'HIGH', 15.036],
       [0, 1, 'HIGH', 33.486],
       [0, 0, 'NORMAL', 18.809],
       [1, 0, 'HIGH', 30.366],
       [0, 2, 'NORMAL', 9.381],
       [0, 1, 'NORMAL', 22.697],
       [1, 1, 'HIGH', 17.951],
       [0, 2, 'NORMAL', 8.75],
       [1, 0, 'HIGH', 9

In [ ]:
y = pd.get_dummies(df.iloc[:,5:]).values
y

array([[0],
       [3],
       [3],
       [4],
       [0],
       [4],
       [0],
       [3],
       [0],
       [0],
       [3],
       [0],
       [0],
       [0],
       [4],
       [0],
       [4],
       [1],
       [3],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [4],
       [2],
       [4],
       [0],
       [4],
       [4],
       [1],
       [4],
       [4],
       [4],
       [0],
       [2],
       [0],
       [4],
       [4],
       [4],
       [1],
       [3],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [2],
       [3],
       [2],
       [0],
       [4],
       [0],
       [0],
       [1],
       [0],
       [4],
       [2],
       [0],
       [1],
       [4],
       [0],
       [0],
       [2],
       [0],
       [4],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [4],
       [2],
       [4],
       [3],
    

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=21)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((160, 4), (40, 4), (160, 1), (40, 1))

In [ ]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(26,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 8)                 40        
                                                                 
 dense_6 (Dense)             (None, 26)                234       
                                                                 
 dense_7 (Dense)             (None, 3)                 81        
                                                                 
Total params: 355
Trainable params: 355
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=21)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape
X_new = np.random.rand(5,4)
y_pred = model.predict(X_new)
print(y_pred)


1/1 [==============================] - 0s 127ms/step
[[0.35417673 0.3806729  0.2651503 ]
 [0.33706933 0.4469745  0.2159562 ]
 [0.33999202 0.382349   0.27765894]
 [0.35866296 0.35300976 0.28832728]
 [0.33034822 0.4240727  0.24557902]]
